export const dataMapping = {
    ai: {
        '1st': [
            { title: "Foundations of Electronics Engineering ", color: "bg-red-200", icon: "⚡" },
            { title: "Engineering Mathematics-I", color: "bg-red-200", icon: "➕" },
            { title: "Learning Programming Concept with C", color: "bg-red-200", icon: "©️" },
            { title: "Fundamentals of Computational Biology", color: "bg-red-200", icon: "🧬" },
            { title: "Environmental Science", color: "bg-red-200", icon: "🌲" },
            { title: "Professional Ethics and Life Skills", color: "bg-red-200", icon: "🚦" },
            { title: "Language & Writing Skills", color: "bg-red-200", icon: "📝" },
        ],
        '3rd': [
            { title: "Probability and Statistics", color: "bg-red-200", icon: "🪙" },
            { title: "Analysis & Design of Algorithm ", color: "bg-red-200", icon: "🎡" },
            { title: "Computer Organization and Architecture  ", color: "bg-red-200", icon: "🖥️" },
            { title: "Discrete Structure ", color: "bg-red-200", icon: "🥏" },
            { title: "Database Management System", color: "bg-red-200", icon: "🗃️" },
        ],
        '5th': [
            { title: "Machine Learning", color: "bg-red-200", icon: "🎍" },
            { title: "Predictive Modeling and Analytics", color: "bg-red-200", icon: "📳" },
            { title: "Cryptography and Network Security", color: "bg-red-200", icon: "🔐" },
            { title: "Artificial Neural Networks", color: "bg-red-200", icon: "🧠" },
            { title: "Deep Learning", color: "bg-red-200", icon: "🤖" },
        ],
        '7th': [
            { title: "Natural Language Processing", color: "bg-red-200", icon: "📝" },
            { title: "Computer Vision", color: "bg-red-200", icon: "👁️" },
            { title: "Reinforcement Learning", color: "bg-red-200", icon: "🎮" },
            { title: "Quantum Computing", color: "bg-red-200", icon: "💫" },
            { title: "Cloud Computing", color: "bg-red-200", icon: "☁️" },
        ],
    },
    ds: {
        '1st': [
            { title: "Foundations of Electronics Engineering ", color: "bg-red-200", icon: "⚡" },
            { title: "Engineering Mathematics-I", color: "bg-red-200", icon: "➕" },
            { title: "Learning Programming Concept with C", color: "bg-red-200", icon: "©️" },
            { title: "Fundamentals of Computational Biology", color: "bg-red-200", icon: "🧬" },
            { title: "Environmental Science", color: "bg-red-200", icon: "🌲" },
            { title: "Professional Ethics and Life Skills", color: "bg-red-200", icon: "🚦" },
            { title: "Language & Writing Skills", color: "bg-red-200", icon: "📝" },
        ],
        '3rd': [
            { title: "Probability and Statistics", color: "bg-red-200", icon: "🪙" },
            { title: "Analysis & Design of Algorithm ", color: "bg-red-200", icon: "🎡" },
            { title: "Computer Organization and Architecture  ", color: "bg-red-200", icon: "🖥️" },
            { title: "Discrete Structure ", color: "bg-red-200", icon: "🥏" },
            { title: "Database Management System", color: "bg-red-200", icon: "🗃️" },
        ],
        '5th': [
            { title: "Pattern Recognition and Machine Learning", color: "bg-red-200", icon: "🔰" },
            { title: "Intelligent Data Analysis", color: "bg-red-200", icon: "🎢" },
            { title: "Cryptography and Network Security", color: "bg-red-200", icon: "🔐" },
            { title: "Natural Language Processing", color: "bg-red-200", icon: "🗣️" },
            { title: "Computational Complexity", color: "bg-red-200", icon: "🎚️" },
        ],
        '7th': [
            { title: " Big Data Analytics ", color: "bg-red-200", icon: "🍃" },
            { title: "Data Wrangling ", color: "bg-red-200", icon: "🧹" },
            { title: "Software Engineering", color: "bg-red-200", icon: "🛋️" },
            { title: "Gaming Theory", color: "bg-red-200", icon: "🎮" },
            { title: " Technical Communication and Soft Skill ", color: "bg-red-200", icon: "🙊" },
        ],
    }
};